# Generated by Django 5.2.6 on 2025-09-20 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_itempedido_options_alter_produto_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cep',
            field=models.CharField(default='00000-000', max_length=9),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cidade',
            field=models.CharField(default='Sem Cidade', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='email_entrega',
            field=models.EmailField(default='sem_email@exemplo.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='endereco',
            field=models.CharField(default='Sem Endereço', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.CharField(default='Sem Estado', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='nome_entrega',
            field=models.CharField(default='Sem Nome', max_length=100),
            preserve_default=False,
        ),
    ]
