# Generated by Django 5.2.6 on 2025-10-01 03:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_pedido_cep_pedido_cidade_pedido_email_entrega_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.AddField(
            model_name='pedido',
            name='bairro',
            field=models.CharField(default='', max_length=100, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='complemento',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='dados_entrega',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Dados de Entrega Completos'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='numero',
            field=models.CharField(default='S/N', max_length=10, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='observacoes',
            field=models.TextField(blank=True, default='', verbose_name='Observações do Pedido'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='preference_id',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Preference ID'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='telefone_entrega',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Telefone para Contato'),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='app.pedido', verbose_name='Pedido'),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='preco_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Preço Unitário'),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.produto', verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='quantidade',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Atualização'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cep',
            field=models.CharField(default='00000-000', max_length=9, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cidade',
            field=models.CharField(default='', max_length=50, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='email_entrega',
            field=models.EmailField(default='exemplo@email.com', max_length=254, verbose_name='E-mail para Contato'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='endereco',
            field=models.CharField(default='', max_length=200, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(default='', max_length=50, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='id_mercado_pago',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='ID do Mercado Pago'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='nome_entrega',
            field=models.CharField(default='', max_length=100, verbose_name='Nome para Entrega'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('processando', 'Processando Pagamento'), ('pago', 'Pago'), ('preparando', 'Preparando Envio'), ('enviado', 'Enviado'), ('entregue', 'Entregue'), ('cancelado', 'Cancelado'), ('reembolsado', 'Reembolsado')], default='pendente', max_length=20, verbose_name='Status do Pedido'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor Total'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Atualização'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='desconto',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Desconto (%)'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='disponivel',
            field=models.BooleanField(default=True, verbose_name='Disponível para Venda'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='estoque',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantidade em Estoque'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/%Y/%m/%d/', verbose_name='Imagem do Produto'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome do Produto'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco_original',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço Original'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['usuario', 'criado_em'], name='app_pedido_usuario_55d0d8_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['status'], name='app_pedido_status_bc862d_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['id_mercado_pago'], name='app_pedido_id_merc_882f1f_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['disponivel', 'estoque'], name='app_produto_disponi_c652e2_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['data_criacao'], name='app_produto_data_cr_ad841e_idx'),
        ),
        migrations.AddConstraint(
            model_name='itempedido',
            constraint=models.UniqueConstraint(fields=('pedido', 'produto'), name='unique_produto_pedido'),
        ),
    ]
