# Generated by Django 5.2.6 on 2025-11-01 22:45

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_pedido_options_pedido_bairro_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código do Cupom')),
                ('tipo', models.CharField(choices=[('percentual', 'Percentual (%)'), ('fixo', 'Valor Fixo (R$)')], default='percentual', max_length=20, verbose_name='Tipo de Desconto')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Valor do Desconto')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_inicio', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Válido a partir de')),
                ('data_fim', models.DateTimeField(blank=True, null=True, verbose_name='Válido até')),
                ('limite_uso', models.PositiveIntegerField(blank=True, null=True, verbose_name='Limite de Uso (total)')),
                ('limite_por_usuario', models.PositiveIntegerField(default=1, verbose_name='Limite por Usuário')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cupom de Desconto',
                'verbose_name_plural': 'Cupons de Desconto',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='pedido',
            name='desconto_cupom',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Desconto do Cupom'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='telefone_entrega',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cupom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='app.cupom', verbose_name='Cupom Aplicado'),
        ),
        migrations.CreateModel(
            name='CupomUso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usado_em', models.DateTimeField(auto_now_add=True)),
                ('cupom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usos', to='app.cupom')),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cupom_uso', to='app.pedido')),
            ],
            options={
                'verbose_name': 'Uso de Cupom',
                'verbose_name_plural': 'Usos de Cupom',
            },
        ),
    ]
