# Generated by Django 5.2.6 on 2025-11-02 00:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_cupom_pedido_desconto_cupom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupom',
            name='data_fim',
            field=models.DateField(blank=True, null=True, verbose_name='Válido até'),
        ),
        migrations.AlterField(
            model_name='cupom',
            name='data_inicio',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Válido a partir de'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='bairro',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cep',
            field=models.CharField(blank=True, default='', max_length=9, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cidade',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='email_entrega',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='E-mail para Contato'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='endereco',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(blank=True, default='', max_length=2, verbose_name='Estado (UF)'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='nome_entrega',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Nome para Entrega'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='numero',
            field=models.CharField(blank=True, default='S/N', max_length=20, verbose_name='Número'),
        ),
    ]
